services:
  mongodb:
    image: 'mongo:8.0-rc-noble'
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGODB_DATABASE_NAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}'
    ports:
      - '27017:27017'
  mysql:
    image: 'mysql:8.0-oracle'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE_NAME}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '3306:3306'
