spring:
  application:
    name: flare
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  datasource:
    uri: "${MYSQL_URI}/${MYSQL_DATABASE_NAME}"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      uri: "${MONGODB_URI}/${MONGODB_DATABASE_NAME}"
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
  mail:
    host: ${MAIL_SERVER_HOST}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  servlet:
    context-path: /api/v1
logging:
  level:
    dev.some.flare: DEBUG   # Specific logging level for the 'dev.some.flare' package
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: INFO

app:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
